backend:
  name: github
  repo: mac-sullivan/el-diablo
  branch: main
  auth_scope: repo
  base_url: https://jazzy-cat-bff998.netlify.app

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
